{{- if .Values.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:metrics-addon:agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:metrics-addon:agent
subjects:
  - kind: ServiceAccount
    name: metrics-addon-sa
    namespace: {{ .Values.addonInstallNamespace }}
{{- end }}
