{{- if .Values.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: multicluster-observability-addon:metrics:agent
  namespace: {{ .Values.addonInstallNamespace }}
  labels:
    {{- include "metricshelm.labels" . | indent 4 }}
    app.kubernetes.io/component: metrics-agent
    app.kubernetes.io/instance: metrics-agent
    app.kubernetes.io/name: metrics-addon-sa
{{- end }}
