{{- if .Values.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: multicluster-observability-metrics
  namespace: {{ .Values.addonInstallNamespace }}
  labels:
    {{- include "metricshelm.labels" . | indent 4 }}
    app.kubernetes.io/component: metrics-agent
{{- end }}
