{{- if .Values.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: multicluster-observability-metrics
  namespace: {{.Release.Namespace }}
  labels:
    {{- include "metricshelm.labels" . | indent 4 }}
{{- end }}
