{{- if .Values.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: metrics-addon-sa
  namespace: {{ .Values.addonInstallNamespace }}
  labels:
    app.kubernetes.io/part-of: multicluster-observability-addon
    app.kubernetes.io/component: metrics-agent
    app.kubernetes.io/instance: metrics-agent
    app.kubernetes.io/name: metrics-addon-sa
{{- end }}
